sudo: required

services:
    - docker

before_install:
    - docker build -t vadimpyl/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vadimpyl/docker-react npm run test -- --coverage

deploy: 
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-eu-central-1-120246917526"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_is: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
    
    
